log:
  level: warning|info|fatal|critical|debug
scheduler:
  aws: '1s'|'1m'|'1h'
  uptimerobot: '1s'|'1m'|'1h'
  ga: '1s'|'1m'|'1h'
  consul: '1s'|'1m'|'1h'
  rdashboard: '1s'|'1m'|'1h'
  github: '1s'|'1m'|'1h'
github:
  user:
  repos: {}
  organizations: {}
  tokens:
    default:
aws:
  region: eu-west-1
  access:
  secret:
  accounts : {}
  elb:
    limit: 20|40|60
  ec2_status:
    - name: "name-aws-ec2"
      status: "running|stopped|..."
consul:
  servers:
    MyNameServer: #(comment to delete) This name is display when agent is unreachable
      name: localhost|fqdn
      port: 8500
      protocol: http://
uptimerobot:
  token:
google:
  analytics:
    service_account_email:
    key_file: config/certs/mycert.p12
    key_secret:
    profileID:
    application_name:
    application_version: 1.0
countdown:
  ie:
    enable: true
    date: 'Jul 27, 2015 00:00:00'
alarms:
  gif_no_alarms:
   enable: true
   mode: lesjoiesdusysadmin
